# Scalar and Vector

Based on: [Marcos Duarte, Renato Naville Watanabe, Laboratory of Biomechanics and Motor Control](https://nbviewer.org/github/BMClab/BMC/blob/master/notebooks/ScalarVector.ipynb)

Python handles very well all mathematical operations with numeric scalars and vectors and you can use [Sympy](http://sympy.org) for similar stuff but with abstract symbols. Let's briefly review scalars and vectors and show how to use Python for numerical calculation.  

For a review about scalars and vectors, see chapter 2 of [Ruina and Rudra's book](http://ruina.tam.cornell.edu/Book/index.html).

## Python setup

In [1]:
from IPython.display import IFrame
import math
import numpy as np

## Scalar

>A **scalar** is a one-dimensional physical quantity, which can be described by a single real number. This means that to describe it, it is enough to state its magnitude. Unlike vector quantities, which have a direction in addition to magnitude, scalars have no directional properties.  
For example, time, mass, and energy are examples of scalars.
    
**Examples of scalar quantities:**
- Length: For example, the length of a pencil is 15 cm.
- Weight: The weight of a book is 500 grams.
- Time: The duration of a movie is 2 hours.
- Temperature: The temperature of water is 20 degrees Celsius.
- Energy: The kinetic energy of a moving body is 100 Joules.
## Extensive and intensive quantities

In thermodynamics and physics, we generally distinguish two basic types of quantities: extensive and intensive. This division is important for understanding the behavior of systems and their properties.

### Extensive quantities

* **Definition:** Extensive quantities are those whose value depends on the size of the system, i.e. on the amount of matter or mass. If we double the amount of matter in the system, the value of the extensive quantity also doubles.

* **Examples:**
    * **Mass (m):** Total mass of a body.
    * **Volume (V):** The space occupied by a body.
    * **Energy (E):** Total energy of a system (internal energy, kinetic energy, potential energy).
    * **Entropy (S):** The degree of disorder of a system.
    * **Charge (Q):** Total electric charge.
    * **Length (l):** Dimension of a body.

### Intensive quantities

* **Definition:** Intensive quantities are those whose value does not depend on the size of the system. They remain the same even if we change the amount of substance in the system.

* **Examples:**
    * **Temperature (T):** The degree of hotness or coldness.
    * **Pressure (p):** The force acting on a unit area.
    * **Density (ρ):** The mass per unit volume.
    * **Specific heat capacity (c):** The amount of heat required to raise a unit mass by 1 degree.
    * **Concentration (c):** The amount of substance in a given volume.

### Relationship between extensive and intensive quantities

* The ratio of two extensive quantities often gives an intensive quantity (e.g. density = mass/volume).
* Intensive quantities are "qualitative" properties, while extensive quantities are "quantitative".

### Practical significance

The distinction between extensive and intensive quantities is crucial for the correct understanding and description of thermodynamic systems and processes. It allows us, for example, to:

* Create thermodynamic models and equations.
* Compare the properties of different substances.
* Predict the behavior of systems under changing conditions.

**Graphical representation of scalars**
Scalars are usually represented graphically as just numbers with the appropriate unit. Unlike vectors, which are represented as lines with orientation, scalars have no direction, and therefore their graphical representation is simple.

### Scalar operations in Python

Simple arithmetic operations with scalars are indeed simple:

In [2]:
a = 2
b = 3
print('a =', a, ', b =', b)
print('a + b =', a + b)
print('a - b =', a - b)
print('a * b =', a * b)
print('a / b =', a / b)
print('a ** b =', a ** b)
print('sqrt(b) =', math.sqrt(b))

a = 2 , b = 3
a + b = 5
a - b = -1
a * b = 6
a / b = 0.6666666666666666
a ** b = 8
sqrt(b) = 1.7320508075688772


If you have a set of numbers, or an array, it is probably better to use Numpy; it will be faster for large data sets, and combined with Scipy, has many more mathematical funcions.

In [3]:
a = 2
b = [3, 4, 5, 6, 7, 8]
b = np.array(b)
print('a =', a, ', b =', b)
print('a + b =', a + b)
print('a - b =', a - b)
print('a * b =', a * b)
print('a / b =', a / b)
print('a ** b =', a ** b)
print('np.sqrt(b) =', np.sqrt(b))  # use numpy functions for numpy arrays

a = 2 , b = [3 4 5 6 7 8]
a + b = [ 5  6  7  8  9 10]
a - b = [-1 -2 -3 -4 -5 -6]
a * b = [ 6  8 10 12 14 16]
a / b = [0.66666667 0.5        0.4        0.33333333 0.28571429 0.25      ]
a ** b = [  8  16  32  64 128 256]
np.sqrt(b) = [1.73205081 2.         2.23606798 2.44948974 2.64575131 2.82842712]


Numpy performs the arithmetic operations of the single number in `a` with all the numbers of the array `b`. This is called broadcasting in computer science.   
Even if you have two arrays (but they must have the same size), Numpy handles for you:

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print('a =', a, ', b =', b)
print('a + b =', a + b)
print('a - b =', a - b)
print('a * b =', a * b)
print('a / b =', a / b)
print('a ** b =', a ** b)

a = [1 2 3] , b = [4 5 6]
a + b = [5 7 9]
a - b = [-3 -3 -3]
a * b = [ 4 10 18]
a / b = [0.25 0.4  0.5 ]
a ** b = [  1  32 729]


## Vector

>A **vector** is a quantity with magnitude (or length) and direction.

For example, position, force, and torque are physical quantities defined by vectors.
What does it means? 
    
**Magnitude**: Specifies the "intensity" or "amount" of the quantity. For example, a speed of 50 km/h indicates the magnitude of the speed.
**Direction**: Specifies where the quantity "points" or "acts". For example, a speed of 50 km/h east indicates both the magnitude and the direction of the movement.
Graphical representation:

A vector is graphically represented as a **oriented abscissa**.

The length of the line segment represents the magnitude of the vector.
The direction of the line segment (and the arrow at its end) represents the direction of the vector.

The symbols for vectors are usually printed in bold in books, such as **a**. Other notation conventions include $\vec {a}$. To avoid misunderstandings, we will denote vectors $\vec{\mathbf{a}}$ in our course.

For example, consider the position of a point in space represented by a vector:

![image.png](https://fyzweb.cz/materialy/sily/sourad/sourad1.gif)

https://fyzweb.cz/materialy/sily/sourad/sourad1.gif

The position of a point represented by a vector in a Cartesian coordinate system.

The position of the point (vector) above can be represented as a triplet of values:

$$ (x,\: y,\: z) \; \Rightarrow \; (5, 3, -2) $$

or in matrix form:

$$ \begin{bmatrix} x \\y \\z \end{bmatrix} \;\; \Rightarrow \;\; \begin{bmatrix} 1 \\3 \\2 \end{bmatrix}$$

We can use Numpy arrays to represent the components of vectors.
For example, for the above vector, it is expressed in Python as:


In [5]:
a = np.array([1, 3, 2])
print('a =', a)


a = [1 3 2]



Exactly like the arrays in the last example for scalars, so all operations we performed will result in the same values, of course.   
However, as we are now dealing with vectors, now some of the  operations dont make sense. For example, for vectors there are no multiplication, division, power, and square root in the way we calculated.

A vector can also be represented as:


Where <span class="notranslate"> $\hat{\mathbf{i}},\, \hat{\mathbf{j}},\, \hat{\mathbf{k}}\,$ </span> are unit vectors, each representing a direction and <span class="notranslate"> $ a_x\hat{\mathbf{i}},\: a_y\hat{\mathbf{j}},\: a_z\hat{\mathbf{k}} $ </span> are the vector components of the vector <span class="notranslate">$\overrightarrow{\mathbf{a}}$</span>.

A unit vector (or versor) is a vector whose length (or norm) is 1.   
The unit vector of a non-zero vector <span class="notranslate">$\overrightarrow{\mathbf{a}}$</span> is the unit vector codirectional with <span class="notranslate">$\overrightarrow{\mathbf{a}}$</span>:


In [6]:
IFrame('https://www.geogebra.org/classic/ydu8a7t7?embed', width='100%', height=500)

## Multiplication of vector by scalar

For the components of the vector ${a_x}\vec{\mathbf{i}}$, we have already used the multiplication of the vector $\vec{\mathbf{i}}$ by the number $a_x$.

> Multiplication of vector by scalar is an operation that changes the magnitude of the vector, but not its direction. We can think of it as "stretching" or "shortening" the vector.

**How ​​it works**:
- **Increase:** When we multiply a vector by a positive scalar (a number greater than 1), we increase its magnitude. It is as if we are "stretching" the vector.
- **Decrease:** When we multiply a vector by a positive scalar between 0 and 1, we decrease its magnitude. It is as if we are "shortening" the vector.
- **Change of direction:** When we multiply a vector by a negative scalar, we change its direction to the opposite. It is as if we are "rotating" the vector by 180 degrees. The magnitude of the vector can also change depending on the absolute value of the scalar.

In [7]:
a = np.array([2,1])
b = 2
c = 0.5
d = -1
print('a * b =', a* b)
print('a * b =', a * c)
print('a * d =', a * d)

a * b = [4 2]
a * b = [1.  0.5]
a * d = [-2 -1]


In [8]:
IFrame('https://www.geogebra.org/classic/HYZXHadK?embed', width='100%', height=500)

If we have a vector $\vec{{\mathbf{a}}}$, there exists an opposite vector $-\vec{{\mathbf{a}}}$. For this vector:
$$\vec{{\mathbf{a}}} + (-\vec{{\mathbf{a}}}) = \vec{{\mathbf{0}}}$$
where $\vec{{\mathbf{0}}}$ is the zero vector $\vec{{\mathbf{0}}} = (0,0,0)$.

Scalar multiplication in Python works simply like array multiplication. However, since we are now dealing with vectors, some operations now don't make sense. For example, there is no multiplication, division, power, or square root for a pair of vectors in the way we calculated them.

The unit vector $\vec{\mathbf{u}}$ of a nonzero vector $\vec{\mathbf{a}}$ is a unit vector with the same direction:

$$ \mathbf{\vec{u}} = \frac{\overrightarrow{\mathbf{a}}}{||\overrightarrow{\mathbf{a}}||} = \frac{a_x\,\hat{\mathbf{i}} + a_y\,\hat{\mathbf{j}} + a_z\, \hat{\mathbf{k}}}{\sqrt{a_x^2+a_y^2+a_z^2}} $$

### Magnitude (length or norm) of a vector

The magnitude (length) of a vector is often represented by the symbol $ || \; || $, also known as the norm (or Euclidean norm) of a vector and is defined as:
$$ ||\overrightarrow{\mathbf{a}}|| = \sqrt{a_x^2+a_y^2+a_z^2} $$
The `numpy.linalg.norm` function calculates the norm:

In [9]:
a = np.array([1, 2, 3])
np.linalg.norm(a)

3.7416573867739413

Or we can use the definition directly and calculate:

In [10]:
np.sqrt(np.sum(a*a))

3.7416573867739413

Then, the eigenvector (unit vector) for the vector $ \overrightarrow{\mathbf{a}} = (1, 2, 3)$ is:

In [11]:
a = np.array([1, 2, 3])
u = a/np.linalg.norm(a)
print('u =', u)

u = [0.26726124 0.53452248 0.80178373]


And we can verify that its size is indeed 1:

In [12]:
np.linalg.norm(u)

1.0

But the representation of a vector as a tuple of values ​​is only valid for a vector with its point of action coinciding with the origin of the coordinate system. $ (0, 0, 0) $.
For example, consider the following vector:
![vector in space](https://images.nagwa.com/figures/explainers/694162356987/6.svg)

Such a vector cannot be represented by $(B_x, B_y, B_z)$, because it would be a vector from the origin to point B. To accurately represent this vector we need two vectors $\vec{OB}$ and $\vec{OA}$. This fact is important when we perform some calculations in mechanics.

### Addition and substraction of vectors

By adding two vectors we will obtain another vector:
$$ \overrightarrow{\mathbf{a}} + \overrightarrow{\mathbf{b}} = (a_x\vec{\mathbf{i}} + a_y\vec{\mathbf{j}} + a_z\vec{\mathbf{k}}) + (b_x\vec{\mathbf{i}} + b_y\vec{\mathbf{j}} + b_z\vec{\mathbf{k}}) = 
(a_x+b_x)\vec{\mathbf{i}} + (a_y+b_y)\vec{\mathbf{j}} + (a_z+b_z)\vec{\mathbf{k}} $$

In matrix notation it will look like this:
$$\begin{bmatrix} a_x \\ a_y \\ a_z \end{bmatrix}  +  \begin{bmatrix} b_x \\ b_y \\ b_z \end{bmatrix} = \begin{bmatrix} a_x + b_x \\ a_y + b_y \\ a_z + b_z \end{bmatrix}$$

The parallelogram method is a graphical method that allows us to visually add two vectors.

**Procedure:**
1. Drawing the vectors: We draw the two vectors that we want to add so that their starting points coincide.
2. Constructing a parallelogram: We construct parallelograms from the endpoints of both vectors. That is, from the endpoint of the first vector we construct a line parallel to the second vector and vice versa. This creates a parallelogram.
3. Resulting vector: The diagonal of the parallelogram, which starts from the point where the two vectors meet, represents the resulting vector (vector sum).

In [13]:
IFrame('https://www.geogebra.org/classic/FCknj7c3?embed', width='100%', height=500)

In space, the parallelogram method works the same way, but we have to construct it in the plane defined by both vectors. Therefore, in space, we prefer to rely on the calculation

In [14]:
IFrame('https://www.geogebra.org/classic/gkhaxb2b?embed', width='100%', height=500)

Subtracting two vectors is also another vector:

$$ \overrightarrow{\mathbf{a}} - \overrightarrow{\mathbf{b}} = (a_x\vec{\mathbf{i}} + a_y\vec{\mathbf{j}} + a_z\vec{\mathbf{k}}) - (b_x\vec{\mathbf{i}} + b_y\vec{\mathbf{j}} + b_z\vec{\mathbf{k}}) = 
(a_x-b_x)\vec{\mathbf{i}} + (a_y-b_y)\vec{\mathbf{j}} + (a_z-b_z)\vec{\mathbf{k}} $$

In matrix form:
$$\begin{bmatrix} a_x \\ a_y \\ a_z \end{bmatrix}  -  \begin{bmatrix} b_x \\ b_y \\ b_z \end{bmatrix} = \begin{bmatrix} a_x - b_x \\ a_y - b_y \\ a_z - b_z \end{bmatrix}$$

Consider two 2D arrays (rows and columns) representing the positions of two objects moving in space. The columns represent the vector components and the rows the values ​​of the position vector at different times. It is easy to perform addition and subtraction with these vectors:

In [15]:
a = np.array([[1, 2, 3], [1, 1, 1]])
b = np.array([[4, 5, 6], [7, 8, 9]])
print('a =', a, '\nb =', b)
print('a + b =', a + b)
print('a - b =', a - b)

a = [[1 2 3]
 [1 1 1]] 
b = [[4 5 6]
 [7 8 9]]
a + b = [[ 5  7  9]
 [ 8  9 10]]
a - b = [[-3 -3 -3]
 [-6 -7 -8]]


Numpy can handle n-dimensional arrays with a size limited by the available memory on the computer.

And we can perform operations on each vector, such as calculating the norm of each one.
First, we check the shape of the variable `a` using the `shape` method or the `numpy.shape` function:

In [16]:
print(a.shape)
print(np.shape(a))

(2, 3)
(2, 3)


This means that variable A has 2 rows and 3 columns. We need to tell the numpy.norm function to calculate the norm for each vector, i.e. to work through the columns of the variable and using the axis parameters:

In [17]:
np.linalg.norm(a, axis=1)

array([3.74165739, 1.73205081])

### Vector between two given points

from [Lesson Explainer: Vectors in Space](https://www.nagwa.com/en/explainers/694162356987/)

Let's start by considering two distinct points a in space, as shown in the figure.
![point AB](https://images.nagwa.com/figures/explainers/694162356987/5.svg)

We want to construct a vector from $A$ to $B$, which is denoted by $\vec{AB}$
![vector AB](https://images.nagwa.com/figures/explainers/694162356987/6.svg)

To achieve this, we can travel through the origin, as shown in the figure below. We can go from point $O$ to point $A$ and then from point $O$ to point
$B$.
![vector AB](https://images.nagwa.com/figures/explainers/694162356987/7.svg)

This can be written as the following equation using vectors:
$$\vec{AB} = \vec{AO} + \vec{OB} $$
For any point $A$,
$$\vec{AO} = - \vec{OA}$$
We can use this property to rewrite our equation as:
$$\vec{AB} = -\vec{OA} + \vec{BO} $$
The vector $\vec{AB}$ can thus be expressed as

$$\vec{AB} = \vec{BO} - \vec{OA} = \vec{\mathbf{B}} - \vec{\mathbf{A}}$$\
The vector between two points can be obtained by subtracting the position vector of the starting point from the position vector of the final point.

In [18]:
IFrame('https://www.geogebra.org/classic/NrzgxrQa?embed', width='100%', height=500)

## Dot Product

>The dot product is an operation that assigns a single number (scalar) to two vectors.

This number tells us how much the two vectors "agree" or "point in the same direction". The dot product allows us to calculate the projection of one vector onto another. This projection tells us how much of one vector "points" in the direction of the other vector.

**Mathematical notation**
The scalar product of the vectors $\vec{\mathbf{u}}$ and $\vec{\mathbf{v}}$ is denoted by $\vec{\mathbf{u}} \cdot \vec{\mathbf{u}}$.

Let us define the scalar product of unit vectors in a rectangular coordinate system.
$$ \vec{\mathbf{i}} \cdot \vec{\mathbf{i}} = \vec{\mathbf{j}} \cdot \vec{\mathbf{j}} = \vec{\mathbf{k}} \cdot \vec{\mathbf{k}}= 1 \quad \text{a} \quad \vec{\mathbf{i}} \cdot \vec{\mathbf{j}} = \vec{\mathbf{i}} \cdot \vec{\mathbf{k}} = \vec{\mathbf{j}} \cdot \vec{\mathbf{k}} = 0 $$

The dot product between two vectors is a mathematical operation algebraically defined as the sum of the multiples of the individual components (in each direction) of both vectors.
$$ \overrightarrow{\mathbf{a}} \cdot \overrightarrow{\mathbf{b}} = (a_x\,\vec{\mathbf{i}}+a_y\,\vec{\mathbf{j}}+a_z\,\vec{\mathbf{k}}) \cdot (b_x\,\vec{\mathbf{i}}+b_y\,\vec{\mathbf{j}}+b_z\,\vec{\mathbf{k}}) = a_x b_x + a_y b_y + a_z b_z $$

The geometric equivalent of the dot product is the product of the magnitudes of the two vectors and the cosine of the angle between them:
$$ \overrightarrow{\mathbf{a}} \cdot \overrightarrow{\mathbf{b}} = ||\overrightarrow{\mathbf{a}}||\:||\overrightarrow{\mathbf{b}}||\:cos(\theta) $$

Which is also equivalent to the dot product of the vector $\overrightarrow{\mathbf{a}}$ and $\overrightarrow{\mathbf{b}}$ is the magnitude of the vector $\overrightarrow{\mathbf{a}}$ and the magnitude of the component $\overrightarrow{\mathbf{b}}$ parallel to $\overrightarrow{\mathbf{a}}$

In matrix notation, we can write it as the multiplication of a pair of vectors
$$ \overrightarrow{\mathbf{a}} \cdot \overrightarrow{\mathbf{b}} = \begin{bmatrix} a_x \\ a_y \\ a_z \end{bmatrix} \begin{bmatrix} b_x \\ b_y \\ b_z \end{bmatrix}^T = \begin{bmatrix} a_x \\ a_y \\ a_z \end{bmatrix} [b_x, b_y, b_z]$$

In this interactive animation, you can visualize the dot product between two vectors:

In [19]:
IFrame('https://www.geogebra.org/classic/ncdf2jsw?embed',
       width='100%', height=500)

The Numpy function for the dot product is `numpy.dot`:

In [20]:
a = np.array([5, 2, 3])
b = np.array([4, 5, 6])
print('a =', a, '\nb =', b)
print('np.dot(a, b) =', np.dot(a, b))

a = [5 2 3] 
b = [4 5 6]
np.dot(a, b) = 48


Or we can use the definition directly and calculate directly:

In [21]:
np.sum(a*b)

48

For 2D arrays, the numpy.dot function performs multiplication rather than dot product; so let's use the numpy.sum function:

In [22]:
a = np.array([[1, 2, 3], [1, 1, 1]])
b = np.array([[4, 5, 6], [7, 8, 9]])
np.sum(a*b, axis=1)

array([32, 24])

## Cross product

> Cross (vector) product is a binary operation defined in three-dimensional Euclidean space that assigns a new vector to two vectors that is perpendicular to both of them. Unlike the scalar product, which results in a number (scalar), the result of a vector product is again a vector.

**Mathematical notation**
The cross product of vectors $\vec{\mathbf{a}}$ and $\vec{\mathbf{b}}$ is denoted by $\vec{\mathbf{a}} \times \vec{\mathbf{b}}$.

**Geometric interpretation**
- **Direction**: The resulting vector is perpendicular to the plane defined by vectors $\vec{\mathbf{a}}$ and $\vec{\mathbf{b}}$. Its direction is determined using the right-hand rule: If we bend the fingers of our right hand from vector u to vector v, the thumb shows us the direction of the resulting vector.

![right-hand rule](https://www.ck12.org//flx/show/THUMB_POSTCARD/image/user%3Af99688690816/28.43.2.png)

- **Magnitude**: The magnitude of the resulting vector is equal to the area of ​​the parallelogram defined by the vectors $\vec{\mathbf{a}}$ and $\vec{\mathbf{b}}$.

$$ \overrightarrow{\mathbf{a}} \times \overrightarrow{\mathbf{b}} = ||\overrightarrow{\mathbf{a}}||\:||\overrightarrow{\mathbf{b}}||\:sin(\theta) $$

<br>
<figure><img src="http://upload.wikimedia.org/wikipedia/commons/4/4e/Cross_product_parallelogram.svg" width=160 alt="Vector subtraction"/><figcaption><i>Fig. The area of ​​a parallelogram is equal to the magnitude of the cross product (source Wikipedia).</i>
</figcaption></figure>

**Analytical expression**

Let's define the cross product of unit vectors:
$$ \begin{array}{l l}
\vec{\mathbf{i}} \times \vec{\mathbf{i}} = \vec{\mathbf{j}} \times \vec{\mathbf{j}} = \vec{\mathbf{k}} \times \vec{\mathbf{k}} = 0 \\
\vec{\mathbf{i}} \times \vec{\mathbf{j}} = \vec{\mathbf{k}}, \quad \vec{\mathbf{k}} \times \vec{\mathbf{k}} = \vec{\mathbf{i}}, \quad \vec{\mathbf{k}} \times \vec{\mathbf{i}} = \vec{\mathbf{j}} \\
\vec{\mathbf{j}} \times \vec{\mathbf{i}} = -\vec{\mathbf{k}}, \quad \vec{\mathbf{k}} \times \vec{\mathbf{j}}= -\vec{\mathbf{i}}, \quad \vec{\mathbf{i}} \times \vec{\mathbf{k}} = -\vec{\mathbf{j}}
\end{array} $$

we then obtain

$$ \overrightarrow{\mathbf{a}} \times \overrightarrow{\mathbf{b}} = (a_x\,\vec{\mathbf{i}} + a_y\,\vec{\mathbf{j}} + a_z\,\vec{\mathbf{k}}) \times (b_x\,\vec{\mathbf{i}}+b_y\,\vec{\mathbf{j}}+b_z\,\vec{\mathbf{k}}) = (a_y b_z-a_z b_y)\vec{\mathbf{i}} + (a_z b_x-a_x b_z)\vec{\mathbf{j}}+(a_x b_y- a_y b_x)\vec{\mathbf{k}} $$

The cross product can also be calculated as the determinant of a matrix:
$$ \overrightarrow{\mathbf{a}} \times \overrightarrow{\mathbf{b}} = \left| \begin{array}{ccc}
\vec{\mathbf{i}} & \vec{\mathbf{j}} & \vec{\mathbf{k}} \\
a_x & a_y & a_z \\
b_x & b_y & b_z
\end{array} \right|
= a_y b_z \vec{\mathbf{i}} + a_z b_x \vec{\mathbf{j}} + a_x b_y \vec{\mathbf{k}} - a_y b_x \vec{\mathbf{k}}-a_z b_y \vec{\mathbf{i}} - a_x b_z \vec{\mathbf{j}} $$
$$\overrightarrow{\mathbf{a}} \times \overrightarrow{\mathbf{b}} = (a_y b_z-a_z b_y)\vec{\mathbf{i}} + (a_z b_x-a_x b_z)\vec{\mathbf{j}} + (a_x b_y-a_y b_x)\vec{\mathbf{k}} $$

In this interactive animation, you can visualize the cross product between two vectors:

In [23]:
IFrame('https://www.geogebra.org/classic/cz6v2U99?embed',
       width='100%', height=500)

The Numpy function for the cross product is `numpy.cross`:

In [24]:
a = [0, 0, 5]
b = [3, 0, 0]

print('a =', a, '\n b =', b)
print('np.cross(a, b) =', np.cross(a, b))

a = [0, 0, 5] 
 b = [3, 0, 0]
np.cross(a, b) = [ 0 15  0]


For a 2D array with vectors in different rows:

In [25]:
a = np.array([[1, 2, 3], [1, 1, 1]])
b = np.array([[4, 5, 6], [7, 8, 9]])
np.cross(a, b, axis=1)

array([[-3,  6, -3],
       [ 1, -2,  1]])

In [26]:
a = np.array([1, 2, 0])
b = np.array([0, 1, 3])
c = np.array([1, 0, 1])

## Further Reading

- Read pages 44-92 of the first chapter of [Ruina and Rudra's book](http://ruina.tam.cornell.edu/Book/index.html) on scalars and vectors in mechanics.

## Video lectures on the Internet

- Khan Academy: [Vectors](https://www.khanacademy.org/math/algebra-home/alg-vectors)
- [Vectors, what even are they?](https://youtu.be/fNk_zzaMoSs)
- [Basics of Vector and Tensor Algebra](https://is.muni.cz/do/rect/el/estud/prif/js17/pocetni_praktikum1/web/ch02.html)

## Problems

1. Given the vectors, $\overrightarrow{\mathbf{a}}=[1, 0, 0]$ and $\overrightarrow{\mathbf{b}}=[1, 1, 1]$, calculate their dot and cross products.

2. Calculate the unit vectors for $ [2, −2, 3] $ and $ [3, −3, 2] $ and determine the orthogonal vector of these two vectors.

3. Given the vectors $a = [1, 0, 0]$ and $b = [1, 1, 1]$, calculate $\overrightarrow{\mathbf{a}} \times \overrightarrow{\mathbf{b}}$ and verify that this vector is orthogonal to the original vectors. Also calculate $\overrightarrow{\mathbf{b}} \times \overrightarrow{\mathbf{a}}$ and compare with $\overrightarrow{\mathbf{a}} \times \overrightarrow{\mathbf{b}}$.

4. Given the vectors $ [1, 1, 0]; [1, 0, 1]; [0, 1, 1] $, calculate the orthonormal basis of the coordinate system.

6. Solve problems **1.1** to **1.9**, **1.11** (using Python), **1.12**, **1.14**, **1.17**, **1.18** to **1.24** of the book Ruina a Rudra

7. From the book Ruina a Rudra, solve problems **1.1.1** to **1.3.16**.

If you are not confident in scalars and vectors, you should solve these problems by hand first and then use Python to check your answers. Knowledge of vector calculus is essential for further mastery of mechanics.

## References

- Ruina A, Rudra P (2019) [Introduction to Statics and Dynamics](http://ruina.tam.cornell.edu/Book/index.html). Oxford University Press.